openapi: 3.0.0
info:
  version: 1.0.0
  title: Solid Trello API

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /lists:
    get:
      operationId: GetAllLists
      tags:
        - "lists"
      description: Get all lists
      responses:
        "200":
          description: Get all lists successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/List"

components:
  schemas:
    List:
      type: object
      required:
        - id
        - title
        - tasks
        - order
      properties:
        id:
          type: number
          example: 1
        title:
          type: string
          example: In Progress
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/Task"
        order:
          type: number
          description: Order of the list in the board
    Task:
      type: object
      required:
        - id
        - title
        - listId
        - order
      properties:
        id:
          type: number
          example: 1
        title:
          type: string
          example: Task 1
        listId:
          type: number
          example: 1
          description: List id associated with this task
        order:
          type: number
          example: 1
          description: Order of this task in the list
