output            = "../db-api/db_models"
wipe              = true
no-tests          = true
add-enum-types    = true
struct-tag-casing = "camel"

[psql]
  dbname    = "trello"
  host      = "localhost"
  port      = 5432
  user      = "postgres"
  pass      = "Test12345"
  sslmode   = "disable"
  schema    = "public"
  blacklist = ["spatial_ref_sys"]